In [2]:
# Importing Libraries
import pandas as pd
import numpy as np
import yfinance as yf
from sklearn.cluster import KMeans

In [3]:
dict_companies={'nippon_india':'GOLDBEES.NS','hdfc_bank':'HDFCBANK.NS','hindustan_unilever':'HINDUNILVR.NS','infosys':'INFY.NS',
               'oil_and_natural_gas_corporation':'ONGC.NS','tcs':'TCS.NS','zomato':'ZOMATO.NS','bank_of_maharashtra':'MAHABANK.NS',
               'trident':'TRIDENT.NS','tata_coffee':'TATACOFFEE.NS','tata_power':'TATAPOWER.NS','apollo_tyres':'APOLLOTYRE.NS',
               'havells':'HAVELLS.NS','justdial':'JUSTDIAL.NS','jubilant_foodworks':'JUBLFOOD.NS','larsen_and_toubro_finance':'L&TFH.NS',
               'coal_india':'COALINDIA.NS','tech_mahindra':'TECHM.NS','axis_bank':'AXISBANK.NS','bajaj_finance':'BAJFINANCE.NS'}

In [4]:
# Importing data
start_date="2023-1-1"
end_date="2023-5-1"
data=yf.Tickers(list(dict_companies.values())).history(period="1d",start=start_date,end=end_date)

[*********************100%***********************]  20 of 20 completed

In [5]:
close=data['Close']
volume=data['Volume']
high=data['High']
low=data['Low']
oopen=data['Open']

In [6]:
data_copy=data.copy

In [7]:
data['Index']=[i for i in range(len(data))]
data.set_index(keys=data['Index'],inplace=True)

In [8]:
data['Close'].T[0](data['Volume'].T[0])

TypeError: 'Series' object is not callable

In [88]:
close.corr(method='pearson')[(close.corr(method='pearson')>0.7) & (close.corr(method='pearson')<1)]

,APOLLOTYRE.NS,AXISBANK.NS,BAJFINANCE.NS,COALINDIA.NS,GOLDBEES.NS,HAVELLS.NS,HDFCBANK.NS,HINDUNILVR.NS,INFY.NS,JUBLFOOD.NS,JUSTDIAL.NS,L&TFH.NS,MAHABANK.NS,ONGC.NS,TATACOFFEE.NS,TATAPOWER.NS,TCS.NS,TECHM.NS,TRIDENT.NS,ZOMATO.NS
APOLLOTYRE.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AXISBANK.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.849914,NaN,NaN,0.867849,NaN,0.832172,NaN,NaN,NaN,0.731835,NaN
BAJFINANCE.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COALINDIA.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.780066,NaN,NaN,NaN,NaN,NaN,NaN
GOLDBEES.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HAVELLS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HDFCBANK.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.769928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HINDUNILVR.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
INFY.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.849051,NaN,NaN,NaN
JUBLFOOD.NS,NaN,0.849914,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.773597,NaN,0.717593,NaN,NaN,NaN,NaN,NaN
JUSTDIAL.NS,NaN,NaN,NaN,NaN,NaN,NaN,0.769928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
L&TFH.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.707798,NaN
MAHABANK.NS,NaN,0.867849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.773597,NaN,NaN,NaN,NaN,0.854477,NaN,NaN,NaN,0.841594,NaN
ONGC.NS,NaN,NaN,NaN,0.780066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TATACOFFEE.NS,NaN,0.832172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.717593,NaN,NaN,0.854477,NaN,NaN,NaN,NaN,NaN,0.781096,NaN
TATAPOWER.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.707450,NaN
TCS.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.849051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TECHM.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRIDENT.NS,NaN,0.731835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.707798,0.841594,NaN,0.781096,0.70745,NaN,NaN,NaN,NaN
ZOMATO.NS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
list(dict_companies.values())

['GOLDBEES.NS',
 'HDFCBANK.NS',
 'HINDUNILVR.NS',
 'INFY.NS',
 'ONGC.NS',
 'TCS.NS',
 'ZOMATO.NS',
 'MAHABANK.NS',
 'TRIDENT.NS',
 'TATACOFFEE.NS',
 'TATAPOWER.NS',
 'APOLLOTYRE.NS',
 'HAVELLS.NS',
 'JUSTDIAL.NS',
 'JUBLFOOD.NS',
 'L&TFH.NS',
 'COALINDIA.NS',
 'TECHM.NS',
 'AXISBANK.NS',
 'BAJFINANCE.NS']

,APOLLOTYRE.NS,AXISBANK.NS,BAJFINANCE.NS,COALINDIA.NS,GOLDBEES.NS,HAVELLS.NS,HDFCBANK.NS,HINDUNILVR.NS,INFY.NS,JUBLFOOD.NS,JUSTDIAL.NS,L&TFH.NS,MAHABANK.NS,ONGC.NS,TATACOFFEE.NS,TATAPOWER.NS,TCS.NS,TECHM.NS,TRIDENT.NS,ZOMATO.NS
Index,,,,,,,,,,,,,,,,,,,,
0,1.012143e+06,3.499140e+06,5.858938e+05,4.210444e+06,5.088292e+06,4.623258e+05,2.192318e+06,6.842614e+05,3.802664e+06,1.783166e+06,90197.549988,6.250806e+06,2.291340e+07,9.631643e+06,3.968766e+05,7.747183e+06,7.127437e+05,1.349620e+06,3.501535e+06,1.875960e+07
1,3.036718e+06,6.928781e+06,7.486872e+05,3.643351e+06,5.165272e+06,9.999801e+05,4.190654e+06,8.243851e+05,4.552653e+06,1.235871e+06,98292.299988,8.123195e+06,5.487859e+07,1.499128e+07,5.849354e+05,7.238664e+06,1.248424e+06,1.440639e+06,3.504231e+06,4.970283e+07
2,3.017190e+06,9.060349e+06,6.778240e+05,9.550673e+06,4.040013e+06,2.422225e+06,5.177410e+06,1.675185e+06,7.061085e+06,1.783758e+06,113859.549988,5.641946e+06,6.040028e+07,1.353602e+07,2.597342e+05,1.422691e+07,1.234917e+06,1.703064e+06,3.467011e+06,4.897584e+07
3,1.184887e+07,6.999930e+06,5.108400e+06,8.815941e+06,4.303171e+06,2.454438e+06,5.472318e+06,2.011077e+06,9.869879e+06,2.849881e+06,76011.450012,6.161668e+06,3.584104e+07,1.632070e+07,8.666471e+05,1.027276e+07,1.829302e+06,1.377047e+06,2.393546e+06,3.444873e+07
4,6.218423e+06,5.788723e+06,2.937902e+06,1.223727e+07,3.457864e+06,1.199811e+06,4.547825e+06,9.943584e+05,6.445162e+06,1.987781e+06,58384.349976,5.243072e+06,2.593891e+07,1.680426e+07,2.618634e+05,9.603243e+06,2.491524e+06,2.347794e+06,2.798958e+06,3.027247e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,1.518445e+06,1.820251e+07,5.508258e+05,2.587262e+06,2.660894e+06,3.495029e+05,1.783961e+07,1.738297e+06,8.315000e+06,2.514281e+06,675981.349976,5.380805e+06,5.836146e+07,7.028600e+06,1.451671e+06,5.017827e+06,1.643851e+06,1.626439e+06,3.879119e+06,4.328754e+07
75,7.698870e+05,3.639527e+07,1.500550e+06,2.571176e+06,3.123021e+06,3.961899e+05,2.517820e+07,1.703588e+06,6.809801e+06,2.627119e+06,259470.799988,2.890917e+06,3.603982e+07,1.016994e+07,9.876205e+05,5.957749e+06,2.027266e+06,1.985200e+06,3.308801e+06,1.990562e+08
76,1.943322e+06,1.946961e+07,9.800630e+05,3.439717e+06,1.868214e+06,6.936389e+05,1.369805e+07,1.248414e+06,5.681420e+06,1.292657e+06,256569.549988,2.922359e+06,1.653960e+07,9.177944e+06,7.431509e+05,4.911035e+06,2.003227e+06,1.590696e+06,3.460125e+06,5.976597e+07
77,1.931570e+06,1.599326e+07,2.833336e+06,3.349606e+06,1.677693e+06,3.529652e+05,2.389688e+07,2.746362e+06,8.021950e+06,1.818544e+06,163018.049988,2.651674e+06,1.491867e+07,6.456985e+06,3.861960e+05,5.215890e+06,2.437634e+06,3.544953e+06,6.451362e+06,8.296916e+07
78,3.536022e+06,2.300498e+07,1.495948e+06,4.771307e+06,1.904679e+06,5.856412e+05,1.395982e+07,3.764384e+06,1.011953e+07,1.573036e+06,135306.000000,6.058412e+06,2.353301e+07,1.265690e+07,5.454299e+05,7.951846e+06,2.934531e+06,5.147274e+06,3.710142e+06,1.909384e+08

In [11]:
close

,APOLLOTYRE.NS,AXISBANK.NS,BAJFINANCE.NS,COALINDIA.NS,GOLDBEES.NS,HAVELLS.NS,HDFCBANK.NS,HINDUNILVR.NS,INFY.NS,JUBLFOOD.NS,JUSTDIAL.NS,L&TFH.NS,MAHABANK.NS,ONGC.NS,TATACOFFEE.NS,TATAPOWER.NS,TCS.NS,TECHM.NS,TRIDENT.NS,ZOMATO.NS
Date,,,,,,,,,,,,,,,,,,,,
2023-01-02,328.250000,941.599976,6553.750000,219.379318,47.169998,1097.833252,1628.699951,2558.399902,1524.000000,505.049988,600.549988,89.849998,30.549999,146.558640,217.649994,211.850006,3196.695557,1009.500000,34.400002,60.299999
2023-01-03,325.399994,962.299988,6606.250000,218.744858,47.630001,1125.114502,1639.349976,2542.050049,1522.550049,507.350006,601.299988,90.400002,32.049999,145.681915,220.350006,211.350006,3245.604980,1023.799988,34.400002,58.950001
2023-01-04,320.049988,957.450012,6571.000000,211.960938,48.070000,1145.862183,1610.050049,2536.100098,1494.800049,499.299988,597.549988,88.500000,31.450001,142.467270,217.199997,208.100006,3248.839111,1020.299988,34.000000,56.349998
2023-01-05,338.250000,949.549988,6100.049805,212.937027,47.779999,1164.166138,1599.699951,2583.699951,1475.199951,503.799988,596.450012,88.599998,31.100000,142.710800,221.149994,207.600006,3245.359863,1011.650024,34.049999,56.200001
2023-01-06,327.750000,939.900024,5980.399902,209.130234,47.500000,1189.502319,1594.400024,2576.449951,1448.500000,498.000000,591.349976,86.900002,30.700001,143.538818,218.449997,205.399994,3147.786377,986.150024,33.700001,55.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-04-24,332.100006,882.299988,5933.750000,231.550003,51.259998,1201.900024,1688.150024,2499.750000,1226.300049,449.750000,664.349976,90.150002,30.100000,160.250000,213.550003,195.850006,3174.800049,1006.099976,30.700001,56.000000
2023-04-25,330.000000,878.349976,6075.250000,230.250000,51.320000,1215.900024,1664.150024,2490.449951,1224.900024,450.100006,678.799988,90.099998,29.900000,160.649994,215.500000,197.649994,3176.000000,997.000000,30.600000,57.750000
2023-04-26,334.850006,887.650024,6055.950195,229.750000,51.480000,1219.900024,1671.800049,2510.800049,1227.550049,444.250000,674.549988,90.300003,29.500000,161.149994,216.850006,198.199997,3198.149902,996.299988,30.400000,58.200001
2023-04-27,341.450012,881.400024,6200.049805,231.750000,51.470001,1221.199951,1681.000000,2468.949951,1246.250000,444.899994,670.049988,90.849998,29.700001,160.050003,219.000000,198.500000,3187.949951,1003.150024,31.100000,60.700001
2023-04-28,346.899994,860.000000,6280.100098,233.100006,51.250000,1230.199951,1687.599976,2457.300049,1252.750000,446.450012,675.000000,92.550003,30.200001,158.949997,220.850006,201.100006,3219.250000,1023.700012,31.100000,64.900002

In [29]:
d1=close.T['2023-01-02'].tolist()

In [27]:
d1_vol=volume.T['2023-01-02'].to_list()

In [30]:
d1

[328.25,
 941.5999755859375,
 6553.75,
 219.3793182373047,
 47.16999816894531,
 1097.833251953125,
 1628.699951171875,
 2558.39990234375,
 1524.0,
 505.04998779296875,
 600.5499877929688,
 89.8499984741211,
 30.549999237060547,
 146.5586395263672,
 217.64999389648438,
 211.85000610351562,
 3196.695556640625,
 1009.5,
 34.400001525878906,
 60.29999923706055]

In [36]:
a=list(dict_companies.values())

In [37]:
a

['GOLDBEES.NS',
 'HDFCBANK.NS',
 'HINDUNILVR.NS',
 'INFY.NS',
 'ONGC.NS',
 'TCS.NS',
 'ZOMATO.NS',
 'MAHABANK.NS',
 'TRIDENT.NS',
 'TATACOFFEE.NS',
 'TATAPOWER.NS',
 'APOLLOTYRE.NS',
 'HAVELLS.NS',
 'JUSTDIAL.NS',
 'JUBLFOOD.NS',
 'L&TFH.NS',
 'COALINDIA.NS',
 'TECHM.NS',
 'AXISBANK.NS',
 'BAJFINANCE.NS']

In [46]:
df=pd.DataFrame(a)

In [48]:
df['close']=d1
df['volume']=d1_vol

In [49]:
df

                0        close    volume
0     GOLDBEES.NS   328.250000   1011815
1     HDFCBANK.NS   941.599976   3498198
2   HINDUNILVR.NS  6553.750000    579340
3         INFY.NS   219.379318   4210225
4         ONGC.NS    47.169998   5088245
5          TCS.NS  1097.833252    461228
6       ZOMATO.NS  1628.699951   2190689
7     MAHABANK.NS  2558.399902    681703
8      TRIDENT.NS  1524.000000   3801140
9   TATACOFFEE.NS   505.049988   1782661
10   TATAPOWER.NS   600.549988     89597
11  APOLLOTYRE.NS    89.849998   6250716
12     HAVELLS.NS    30.549999  22913370
13    JUSTDIAL.NS   146.558640   9631496
14    JUBLFOOD.NS   217.649994    396659
15       L&TFH.NS   211.850006   7746971
16   COALINDIA.NS  3196.695557    709547
17       TECHM.NS  1009.500000   1348611
18    AXISBANK.NS    34.400002   3501501
19  BAJFINANCE.NS    60.299999  18759536